#!/bin/sh

### BEGIN INIT INFO
# Provides:        trafficshaper
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start trafficshaper
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

case "$1" in
  start)
    start-stop-daemon --start --exec rest.py --pidfile /var/run/trafficshaper.pid -d /opt/trafficshaper --user trafficshaper --name trafficshaper --background
    /opt/trafficshaper/trafficshaper_init.sh
    ;;
  stop)
    start-stop-daemon --stop --pidfile /var/run/trafficshaper.pid
    ;;
  status)
    start-stop-daemon --status --pidfile /var/run/trafficshaper.pid
    ;;
  *)
    echo "Usage: $0 start|stop|status" >&2
    exit 3
    ;;
esac
